/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
  darkMode: ['selector', '[data-theme="dark"]'],
  theme: {
    extend: {
      colors: {
        brand: {
          50: 'var(--kb-brand-50)',
          100: 'var(--kb-brand-100)',
          200: 'var(--kb-brand-200)',
          300: 'var(--kb-brand-300)',
          400: 'var(--kb-brand-400)',
          500: 'var(--kb-brand-500)',
          600: 'var(--kb-brand-600)',
          700: 'var(--kb-brand-700)',
          800: 'var(--kb-brand-800)',
          900: 'var(--kb-brand-900)',
        },
        pomodoro: { DEFAULT: '#F43F5E', light: '#FDA4AF' },
        note: { DEFAULT: '#2563EB', light: '#93C5FD' },
        flashcard: { DEFAULT: '#06B6D4', light: '#67E8F9' },
        feynman: { DEFAULT: '#6366F1', light: '#A5B4FC' },
        bg: {
          primary: 'var(--kb-bg-primary)',
          secondary: 'var(--kb-bg-secondary)',
          tertiary: 'var(--kb-bg-tertiary)',
          elevated: 'var(--kb-bg-elevated)',
        },
        text: {
          primary: 'var(--kb-text-primary)',
          secondary: 'var(--kb-text-secondary)',
          tertiary: 'var(--kb-text-tertiary)',
          inverse: 'var(--kb-text-inverse)',
        },
        border: {
          DEFAULT: 'var(--kb-border-default)',
          strong: 'var(--kb-border-strong)',
        },
        semantic: {
          success: 'var(--kb-color-success)',
          warning: 'var(--kb-color-warning)',
          error: 'var(--kb-color-error)',
          info: 'var(--kb-color-info)',
        },
      },
      fontFamily: {
        sans: ['var(--kb-font-sans)'],
        mono: ['var(--kb-font-mono)'],
        timer: ['var(--kb-font-timer)'],
      },
      fontSize: {
        'd1': 'var(--kb-text-d1)',
        'd2': 'var(--kb-text-d2)',
        'h1': 'var(--kb-text-h1)',
        'h2': 'var(--kb-text-h2)',
        'h3': 'var(--kb-text-h3)',
        'b1': 'var(--kb-text-b1)',
        'b2': 'var(--kb-text-b2)',
        'b3': 'var(--kb-text-b3)',
        'c1': 'var(--kb-text-c1)',
        'c2': 'var(--kb-text-c2)',
        'timer': 'var(--kb-text-timer)',
      },
      spacing: {
        'kb-xs': 'var(--kb-space-xs)',
        'kb-sm': 'var(--kb-space-sm)',
        'kb-md': 'var(--kb-space-md)',
        'kb-lg': 'var(--kb-space-lg)',
        'kb-xl': 'var(--kb-space-xl)',
        'kb-2xl': 'var(--kb-space-2xl)',
      },
      borderRadius: {
        'kb-sm': 'var(--kb-radius-sm)',
        'kb-md': 'var(--kb-radius-md)',
        'kb-lg': 'var(--kb-radius-lg)',
        'kb-xl': 'var(--kb-radius-xl)',
        'kb-full': 'var(--kb-radius-full)',
      },
      boxShadow: {
        'kb-sm': 'var(--kb-shadow-sm)',
        'kb-md': 'var(--kb-shadow-md)',
        'kb-lg': 'var(--kb-shadow-lg)',
      },
      transitionDuration: {
        'kb-fast': 'var(--kb-duration-fast)',
        'kb-normal': 'var(--kb-duration-normal)',
        'kb-slow': 'var(--kb-duration-slow)',
      },
      transitionTimingFunction: {
        'kb-default': 'var(--kb-ease-default)',
        'kb-in': 'var(--kb-ease-in)',
        'kb-out': 'var(--kb-ease-out)',
        'kb-in-out': 'var(--kb-ease-in-out)',
      },
      width: {
        'icon-xs': 'var(--kb-icon-size-xs)',
        'icon-sm': 'var(--kb-icon-size-sm)',
        'icon-md': 'var(--kb-icon-size-md)',
        'icon-lg': 'var(--kb-icon-size-lg)',
        'icon-xl': 'var(--kb-icon-size-xl)',
      },
      height: {
        'icon-xs': 'var(--kb-icon-size-xs)',
        'icon-sm': 'var(--kb-icon-size-sm)',
        'icon-md': 'var(--kb-icon-size-md)',
        'icon-lg': 'var(--kb-icon-size-lg)',
        'icon-xl': 'var(--kb-icon-size-xl)',
      },
      strokeWidth: {
        'kb-icon': 'var(--kb-icon-stroke-width)',
      },
    },
  },
  plugins: [],
}
