/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
  darkMode: ['selector', '[data-theme="dark"]'],
  theme: {
    extend: {
      colors: {
        brand: {
          50: 'var(--kb-brand-50)',
          100: 'var(--kb-brand-100)',
          200: 'var(--kb-brand-200)',
          300: 'var(--kb-brand-300)',
          400: 'var(--kb-brand-400)',
          500: 'var(--kb-brand-500)',
          600: 'var(--kb-brand-600)',
          700: 'var(--kb-brand-700)',
          800: 'var(--kb-brand-800)',
          900: 'var(--kb-brand-900)',
        },
        accent: {
          50: 'var(--kb-accent-50)',
          100: 'var(--kb-accent-100)',
          200: 'var(--kb-accent-200)',
          300: 'var(--kb-accent-300)',
          400: 'var(--kb-accent-400)',
          500: 'var(--kb-accent-500)',
          600: 'var(--kb-accent-600)',
          700: 'var(--kb-accent-700)',
          800: 'var(--kb-accent-800)',
          900: 'var(--kb-accent-900)',
        },
        pomodoro: { DEFAULT: '#FF6B6B', light: '#FFA8A8' },
        note: { DEFAULT: '#4FB0FF', light: '#ADD6FF' },
        flashcard: { DEFAULT: '#00D2D3', light: '#80E8E8' },
        feynman: { DEFAULT: '#FF7F50', light: '#FFB8A0' },
        bg: {
          primary: 'var(--kb-bg-primary)',
          secondary: 'var(--kb-bg-secondary)',
          tertiary: 'var(--kb-bg-tertiary)',
          elevated: 'var(--kb-bg-elevated)',
        },
        text: {
          primary: 'var(--kb-text-primary)',
          secondary: 'var(--kb-text-secondary)',
          tertiary: 'var(--kb-text-tertiary)',
          inverse: 'var(--kb-text-inverse)',
        },
        border: {
          DEFAULT: 'var(--kb-border-default)',
          strong: 'var(--kb-border-strong)',
        },
        semantic: {
          success: 'var(--kb-color-success)',
          warning: 'var(--kb-color-warning)',
          error: 'var(--kb-color-error)',
          info: 'var(--kb-color-info)',
        },
      },
      fontFamily: {
        sans: ['var(--kb-font-sans)'],
        mono: ['var(--kb-font-mono)'],
        timer: ['var(--kb-font-timer)'],
      },
      fontSize: {
        'd1': 'var(--kb-text-d1)',
        'd2': 'var(--kb-text-d2)',
        'h1': 'var(--kb-text-h1)',
        'h2': 'var(--kb-text-h2)',
        'h3': 'var(--kb-text-h3)',
        'b1': 'var(--kb-text-b1)',
        'b2': 'var(--kb-text-b2)',
        'b3': 'var(--kb-text-b3)',
        'c1': 'var(--kb-text-c1)',
        'c2': 'var(--kb-text-c2)',
        'timer': 'var(--kb-text-timer)',
      },
      spacing: {
        'kb-xs': 'var(--kb-space-xs)',
        'kb-sm': 'var(--kb-space-sm)',
        'kb-md': 'var(--kb-space-md)',
        'kb-lg': 'var(--kb-space-lg)',
        'kb-xl': 'var(--kb-space-xl)',
        'kb-2xl': 'var(--kb-space-2xl)',
      },
      borderRadius: {
        'kb-sm': 'var(--kb-radius-sm)',
        'kb-md': 'var(--kb-radius-md)',
        'kb-lg': 'var(--kb-radius-lg)',
        'kb-xl': 'var(--kb-radius-xl)',
        'kb-full': 'var(--kb-radius-full)',
      },
      boxShadow: {
        'kb-sm': 'var(--kb-shadow-sm)',
        'kb-md': 'var(--kb-shadow-md)',
        'kb-lg': 'var(--kb-shadow-lg)',
        'brand': 'var(--kb-shadow-brand)',
        'accent': 'var(--kb-shadow-accent)',
      },
      transitionDuration: {
        'kb-fast': 'var(--kb-duration-fast)',
        'kb-normal': 'var(--kb-duration-normal)',
        'kb-slow': 'var(--kb-duration-slow)',
      },
      transitionTimingFunction: {
        'kb-default': 'var(--kb-ease-default)',
        'kb-in': 'var(--kb-ease-in)',
        'kb-out': 'var(--kb-ease-out)',
        'kb-in-out': 'var(--kb-ease-in-out)',
        'kb-bounce': 'var(--kb-ease-bounce)',
        'kb-smooth': 'var(--kb-ease-smooth)',
        'kb-spring': 'var(--kb-ease-spring)',
      },
      animation: {
        'scale-bounce': 'scale-bounce var(--kb-duration-normal) var(--kb-ease-bounce)',
        'stagger-in': 'stagger-in var(--kb-duration-normal) var(--kb-ease-smooth)',
        'pulse-skeleton': 'pulse-skeleton 1.5s ease-in-out infinite',
        'shimmer': 'shimmer 2s linear infinite',
        'fade-in-up': 'fade-in-up var(--kb-duration-normal) var(--kb-ease-smooth)',
        'modal-enter': 'modal-enter var(--kb-duration-slow) var(--kb-ease-spring)',
        'card-exit': 'card-exit 350ms var(--kb-ease-in) forwards',
        'brand-draw': 'brand-draw 1.2s ease-out forwards',
        'brand-float': 'brand-float 3s ease-in-out infinite',
        'breathe': 'breathe 2s ease-in-out infinite',
      },
      width: {
        'icon-xs': 'var(--kb-icon-size-xs)',
        'icon-sm': 'var(--kb-icon-size-sm)',
        'icon-md': 'var(--kb-icon-size-md)',
        'icon-lg': 'var(--kb-icon-size-lg)',
        'icon-xl': 'var(--kb-icon-size-xl)',
      },
      height: {
        'icon-xs': 'var(--kb-icon-size-xs)',
        'icon-sm': 'var(--kb-icon-size-sm)',
        'icon-md': 'var(--kb-icon-size-md)',
        'icon-lg': 'var(--kb-icon-size-lg)',
        'icon-xl': 'var(--kb-icon-size-xl)',
      },
      strokeWidth: {
        'kb-icon': 'var(--kb-icon-stroke-width)',
      },
    },
  },
  plugins: [],
}
